"""Helpers for rendering the ablation scientific report."""

from .cli import main, parse_args
from .data import compute_style_hed_scores_local, load_dataset_summary, load_fud_scores
from .figures import (
    build_channel_effect_heatmaps_figure,
    build_comparison_table_figure,
    build_dataset_summary_figure,
    build_leave_one_out_figure,
    build_metric_trends_figure,
    export_report_png_pages,
)
from .html_report import (
    render_comparison_table,
    render_dataset_section,
    render_report_html,
    render_takeaway_text,
)
from .shared import (
    CHANNEL_EFFECT_CMAP,
    DEFAULT_METRIC_ORDER,
    FOUR_GROUP_ORDER,
    GROUP_COLORS,
    GROUP_LABELS,
    GROUP_SHORT_LABELS,
    INK,
    METRIC_COLORS,
    METRIC_LABELS,
    METRIC_SPEC_BY_KEY,
    OKABE_BLUE,
    OKABE_GRAY,
    OKABE_GREEN,
    OKABE_ORANGE,
    OKABE_PURPLE,
    OKABE_RED,
    OKABE_TEAL,
    ROOT,
    SOFT_GRID,
    TRADEOFF_HIGHER_IS_BETTER,
    TRADEOFF_METRIC_ORDER,
    TRADEOFF_REFERENCE_BANDS,
    DatasetSummary,
    comparison_metric_keys,
    compact_condition_order_label,
    condition_order_label,
    format_condition,
    humanize_token,
    metric_tradeoff_keys,
    plain_takeaway_text,
)

__all__ = [
    "CHANNEL_EFFECT_CMAP",
    "DEFAULT_METRIC_ORDER",
    "FOUR_GROUP_ORDER",
    "GROUP_COLORS",
    "GROUP_LABELS",
    "GROUP_SHORT_LABELS",
    "INK",
    "METRIC_COLORS",
    "METRIC_LABELS",
    "METRIC_SPEC_BY_KEY",
    "OKABE_BLUE",
    "OKABE_GRAY",
    "OKABE_GREEN",
    "OKABE_ORANGE",
    "OKABE_PURPLE",
    "OKABE_RED",
    "OKABE_TEAL",
    "ROOT",
    "SOFT_GRID",
    "TRADEOFF_HIGHER_IS_BETTER",
    "TRADEOFF_METRIC_ORDER",
    "TRADEOFF_REFERENCE_BANDS",
    "DatasetSummary",
    "build_channel_effect_heatmaps_figure",
    "build_comparison_table_figure",
    "build_dataset_summary_figure",
    "build_leave_one_out_figure",
    "build_metric_trends_figure",
    "comparison_metric_keys",
    "compact_condition_order_label",
    "compute_style_hed_scores_local",
    "condition_order_label",
    "export_report_png_pages",
    "format_condition",
    "humanize_token",
    "load_dataset_summary",
    "load_fud_scores",
    "main",
    "metric_tradeoff_keys",
    "parse_args",
    "plain_takeaway_text",
    "render_comparison_table",
    "render_dataset_section",
    "render_report_html",
    "render_takeaway_text",
]
